const CORRECT_HEADER_1 = 'Program Identifier|Data Source|Card Number|Member ID|First Name|Last Name|Date of Birth|Address 1|Address 2|City|State|Zip code|Telephone number|Email Address|CONSENT|Mobile Phone';
const CORRECT_HEADER_2 = 'Program Identifier|Data Source|Card Number|Member ID|First Name|Last Name|Date of Birth|Address 1|Address 2|City|State|Zip code|Telephone number|Email Address|CONSENT|Mobile Phone|One more field';
const WRONG_HEADER_1 = 'First field|Program Identifier|Data Source|Card Number|Member ID|First Name|Last Name|Date of Birth|Address 1|Address 2|City|State|Zip code|Telephone number|Email Address|CONSENT|Mobile Phone';
const WRONG_HEADER_2 = 'Card Number|Member ID|First Name|Last Name|Date of Birth|Address 1|Address 2|City|State|Zip code|Telephone number|Email Address|CONSENT|Mobile Phone';
const WRONG_HEADER_3 = 'bad value';

// This is bunch of data for testing
const FIELD_VALUE_EMPTY = '';

const PROGRAM_ID_CORRECT = '50777445';
const PROGRAM_ID_WRONG = 'abcdefgh';

const DATA_SOURCE = 'WEB 3RD PARTY';

const CARD_NUMBER_CORRECT = '342121211';
const CARD_NUMBER_WRONG = 'abcdefghz';

const MEMBER_ID_CORRECT = '43233';
const MEMBER_ID_WRONG = 'abcde';

const FIRST_NAME = 'LOAD';

const LAST_NAME = 'TEST 0';

const DATE_OF_BIRTH_CORRECT = '04/29/2000';
const DATE_OF_BIRTH_WRONG = '04.29.2000';

const ADDRESS_1 = '3100 S Ashley Drive';

const ADDRESS_2 = 'APP 1';

const CITY = 'Chandler';

const STATE_CORRECT = 'AZ';
const STATE_WRONG = 'ZZ';

const ZIP_CODE_CORRECT = '85286';
const ZIP_CODE_WRONG = '85286a';

const TEL_NUMBER = '1234567912';

const EMAIL_CORRECT = 'test0@humancaresystems.com';
const EMAIL_WRONG = 'test0.humancaresystems.com';

const CONSENT_Y = 'Y';
const CONSENT_N = 'A';

const MOBILE_NUMBER = '1234567912';

const CORRECT_LINE_WITH_CONSENT_Y =
  `${PROGRAM_ID_CORRECT}|${DATA_SOURCE}|${CARD_NUMBER_CORRECT}|${MEMBER_ID_CORRECT}|${FIRST_NAME}|` +
  `${LAST_NAME}|${DATE_OF_BIRTH_CORRECT}|${ADDRESS_1}|${ADDRESS_2}|${CITY}|${STATE_CORRECT}|${ZIP_CODE_CORRECT}|` +
  `${TEL_NUMBER}|${EMAIL_CORRECT}|${CONSENT_Y}|${MOBILE_NUMBER}`;
const CORRECT_LINE_WITH_CONSENT_N =
  `${PROGRAM_ID_CORRECT}|${DATA_SOURCE}|${CARD_NUMBER_CORRECT}|${MEMBER_ID_CORRECT}|${FIRST_NAME}|` +
  `${LAST_NAME}|${DATE_OF_BIRTH_CORRECT}|${ADDRESS_1}|${ADDRESS_2}|${CITY}|${STATE_CORRECT}|${ZIP_CODE_CORRECT}|` +
  `${TEL_NUMBER}|${EMAIL_CORRECT}|${CONSENT_N}|${MOBILE_NUMBER}`;
const CORRECT_LINE_WITH_EMPTY_FIELDS =
  `${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${MEMBER_ID_CORRECT}|${FIELD_VALUE_EMPTY}|` +
  `${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|` +
  `${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|` +
  `${FIELD_VALUE_EMPTY}`;
const WRONG_LINE_WITH_INCOMPATIBLE_FORMAT = `${FIELD_VALUE_EMPTY}`;
const WRONG_LINE_WITH_EMPTY_MEMBER_ID =
  `${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|` +
  `${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|` +
  `${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${FIELD_VALUE_EMPTY}|${CONSENT_Y}|` +
  `${FIELD_VALUE_EMPTY}`;
const WRONG_LINE_WITH_WRONG_PROGRAM_ID =
  `${PROGRAM_ID_WRONG}|${DATA_SOURCE}|${CARD_NUMBER_CORRECT}|${MEMBER_ID_CORRECT}|${FIRST_NAME}|` +
  `${LAST_NAME}|${DATE_OF_BIRTH_CORRECT}|${ADDRESS_1}|${ADDRESS_2}|${CITY}|${STATE_CORRECT}|${ZIP_CODE_CORRECT}|` +
  `${TEL_NUMBER}|${EMAIL_CORRECT}|${CONSENT_Y}|${MOBILE_NUMBER}`;
const WRONG_LINE_WITH_WRONG_CARD_NUMBER =
  `${PROGRAM_ID_CORRECT}|${DATA_SOURCE}|${CARD_NUMBER_WRONG}|${MEMBER_ID_CORRECT}|${FIRST_NAME}|` +
  `${LAST_NAME}|${DATE_OF_BIRTH_CORRECT}|${ADDRESS_1}|${ADDRESS_2}|${CITY}|${STATE_CORRECT}|${ZIP_CODE_CORRECT}|` +
  `${TEL_NUMBER}|${EMAIL_CORRECT}|${CONSENT_Y}|${MOBILE_NUMBER}`;
const WRONG_LINE_WITH_WRONG_MEMBER_ID =
  `${PROGRAM_ID_CORRECT}|${DATA_SOURCE}|${CARD_NUMBER_CORRECT}|${MEMBER_ID_WRONG}|${FIRST_NAME}|` +
  `${LAST_NAME}|${DATE_OF_BIRTH_CORRECT}|${ADDRESS_1}|${ADDRESS_2}|${CITY}|${STATE_CORRECT}|${ZIP_CODE_CORRECT}|` +
  `${TEL_NUMBER}|${EMAIL_CORRECT}|${CONSENT_Y}|${MOBILE_NUMBER}`;
const WRONG_LINE_WITH_WRONG_DATE_OF_BIRTH =
  `${PROGRAM_ID_CORRECT}|${DATA_SOURCE}|${CARD_NUMBER_CORRECT}|${MEMBER_ID_CORRECT}|${FIRST_NAME}|` +
  `${LAST_NAME}|${DATE_OF_BIRTH_WRONG}|${ADDRESS_1}|${ADDRESS_2}|${CITY}|${STATE_CORRECT}|${ZIP_CODE_CORRECT}|` +
  `${TEL_NUMBER}|${EMAIL_CORRECT}|${CONSENT_Y}|${MOBILE_NUMBER}`;
const WRONG_LINE_WITH_WRONG_STATE =
  `${PROGRAM_ID_CORRECT}|${DATA_SOURCE}|${CARD_NUMBER_CORRECT}|${MEMBER_ID_CORRECT}|${FIRST_NAME}|` +
  `${LAST_NAME}|${DATE_OF_BIRTH_CORRECT}|${ADDRESS_1}|${ADDRESS_2}|${CITY}|${STATE_WRONG}|${ZIP_CODE_CORRECT}|` +
  `${TEL_NUMBER}|${EMAIL_CORRECT}|${CONSENT_Y}|${MOBILE_NUMBER}`;
const WRONG_LINE_WITH_WRONG_ZIP_CODE =
  `${PROGRAM_ID_CORRECT}|${DATA_SOURCE}|${CARD_NUMBER_CORRECT}|${MEMBER_ID_CORRECT}|${FIRST_NAME}|` +
  `${LAST_NAME}|${DATE_OF_BIRTH_CORRECT}|${ADDRESS_1}|${ADDRESS_2}|${CITY}|${STATE_CORRECT}|${ZIP_CODE_WRONG}|` +
  `${TEL_NUMBER}|${EMAIL_CORRECT}|${CONSENT_Y}|${MOBILE_NUMBER}`;
const WRONG_LINE_WITH_WRONG_EMAIL =
  `${PROGRAM_ID_CORRECT}|${DATA_SOURCE}|${CARD_NUMBER_CORRECT}|${MEMBER_ID_CORRECT}|${FIRST_NAME}|` +
  `${LAST_NAME}|${DATE_OF_BIRTH_CORRECT}|${ADDRESS_1}|${ADDRESS_2}|${CITY}|${STATE_CORRECT}|${ZIP_CODE_CORRECT}|` +
  `${TEL_NUMBER}|${EMAIL_WRONG}|${CONSENT_Y}|${MOBILE_NUMBER}`;

const PARSED_PATIENT_WITH_CONSENT_Y = {
  programId: PROGRAM_ID_CORRECT,
  dataSource: DATA_SOURCE,
  cardNumber: CARD_NUMBER_CORRECT,
  memberId: MEMBER_ID_CORRECT,
  firstName: FIRST_NAME,
  lastName: LAST_NAME,
  dateOfBirth: DATE_OF_BIRTH_CORRECT,
  address1: ADDRESS_1,
  address2: ADDRESS_2,
  city: CITY,
  state: STATE_CORRECT,
  zipCode: ZIP_CODE_CORRECT,
  telephoneNumber: TEL_NUMBER,
  emailAddress: EMAIL_CORRECT,
  consent: true,
  mobilePhone: MOBILE_NUMBER,
};

const PARSED_PATIENT_EMAILS = [
  { memberId: MEMBER_ID_CORRECT, dayNumber: 1, data: {} },
  { memberId: MEMBER_ID_CORRECT, dayNumber: 2, data: {} },
  { memberId: MEMBER_ID_CORRECT, dayNumber: 3, data: {} },
  { memberId: MEMBER_ID_CORRECT, dayNumber: 4, data: {} },
];

const PARSED_PATIENT_WITH_CONSENT_N = {
  programId: PROGRAM_ID_CORRECT,
  dataSource: DATA_SOURCE,
  cardNumber: CARD_NUMBER_CORRECT,
  memberId: MEMBER_ID_CORRECT,
  firstName: FIRST_NAME,
  lastName: LAST_NAME,
  dateOfBirth: DATE_OF_BIRTH_CORRECT,
  address1: ADDRESS_1,
  address2: ADDRESS_2,
  city: CITY,
  state: STATE_CORRECT,
  zipCode: ZIP_CODE_CORRECT,
  telephoneNumber: TEL_NUMBER,
  emailAddress: EMAIL_CORRECT,
  consent: false,
  mobilePhone: MOBILE_NUMBER,
};

const PARSED_PATIENT_WITH_EMPTY_VALUES = {
  programId: FIELD_VALUE_EMPTY,
  dataSource: FIELD_VALUE_EMPTY,
  cardNumber: FIELD_VALUE_EMPTY,
  memberId: MEMBER_ID_CORRECT,
  firstName: FIELD_VALUE_EMPTY,
  lastName: FIELD_VALUE_EMPTY,
  dateOfBirth: FIELD_VALUE_EMPTY,
  address1: FIELD_VALUE_EMPTY,
  address2: FIELD_VALUE_EMPTY,
  city: FIELD_VALUE_EMPTY,
  state: FIELD_VALUE_EMPTY,
  zipCode: FIELD_VALUE_EMPTY,
  telephoneNumber: FIELD_VALUE_EMPTY,
  emailAddress: FIELD_VALUE_EMPTY,
  consent: false,
  mobilePhone: FIELD_VALUE_EMPTY,
};

module.exports = {
  CORRECT_HEADER_1,
  CORRECT_HEADER_2,
  WRONG_HEADER_1,
  WRONG_HEADER_2,
  WRONG_HEADER_3,
  CORRECT_LINE_WITH_CONSENT_Y,
  CORRECT_LINE_WITH_CONSENT_N,
  CORRECT_LINE_WITH_EMPTY_FIELDS,
  WRONG_LINE_WITH_INCOMPATIBLE_FORMAT,
  WRONG_LINE_WITH_EMPTY_MEMBER_ID,
  WRONG_LINE_WITH_WRONG_PROGRAM_ID,
  WRONG_LINE_WITH_WRONG_CARD_NUMBER,
  WRONG_LINE_WITH_WRONG_MEMBER_ID,
  WRONG_LINE_WITH_WRONG_DATE_OF_BIRTH,
  WRONG_LINE_WITH_WRONG_STATE,
  WRONG_LINE_WITH_WRONG_ZIP_CODE,
  WRONG_LINE_WITH_WRONG_EMAIL,
  PARSED_PATIENT_WITH_CONSENT_Y,
  PARSED_PATIENT_EMAILS,
  PARSED_PATIENT_WITH_CONSENT_N,
  PARSED_PATIENT_WITH_EMPTY_VALUES,
};
